<%
FULL_NAME_CAPS = "_"..string.upper(this.namespace).."_"
FULL_NAME_CAMEL = capitalizedString(this.namespace)
%>
//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

import Foundation
import PlanetSwift

private let xmlCache = NSCache()

public class <%= FULL_NAME_CAMEL %> {

	public class func readFromFile(filePath: String, prepare: Bool = true) -> GaxbElement? {
		do {
			let xmlString = try String(contentsOfFile: filePath, encoding: NSUTF8StringEncoding)
			return <%= FULL_NAME_CAMEL %>.readFromString(xmlString)
		} catch {
				return nil
		}
	}

	public class func readFromString(string: String, prepare: Bool = true) -> GaxbElement? {

		if let cachedElement = xmlCache.objectForKey(string) as? GaxbElement {
			let copiedCache = cachedElement.copy()
			if prepare {
				copiedCache.visit() { $0.gaxbPrepare() }
			}
			return copiedCache
		}

		if let xmlData = <%= FULL_NAME_CAMEL %>.processExpressions(string).dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false) {
			do {
				let xmlDoc = try AEXMLDocument(xmlData: xmlData, processNamespaces: true)
				if let parsedElement = <%= FULL_NAME_CAMEL %>.parseElement(xmlDoc.root) {
					xmlCache.setObject(parsedElement as! AnyObject, forKey:string)
					let copiedElement = parsedElement.copy()
					if prepare {
						copiedElement.visit() { $0.gaxbPrepare() }
					}
					return copiedElement
				}
			} catch {
				return nil
			}
		}
		return nil
	}


	public class func namespaceForElement(element: AEXMLElement) -> String {
		if let namespace = element.namespaceURI?.lastPathComponent {
			return namespace
		}
		return "<%= FULL_NAME_CAMEL %>"
	}

	public class func parseElement(element: AEXMLElement) -> GaxbElement? {
		let namespace = self.namespaceForElement(element)
		if let entity : GaxbElement = GaxbFactory.element(namespace, name:element.name) {
			for (attribute, value) in element.attributes {
				if let valueString = value as? String, attributeString = attribute as? String {
					entity.setAttribute(valueString, key: attributeString)
				}
			}
			for child in element.children {
				if let subEntity = <%= FULL_NAME_CAMEL %>.parseElement(child) {
					entity.setElement(subEntity, key: child.name)
				}
			}
			return entity
		}
		return nil
	}

<%
	-- simpleType definitions, such as enums
	for k,v in pairs(schema.simpleTypes) do
		-- only include defintions from this schema's namespace
		if (isEnumForItem(v)) then
			if (schema.namespace == v.namespace) then

				gaxb_print("\tpublic enum "..v.name..": String {\n");

				local appinfo = gaxb_xpath(v.xml, "./XMLSchema:annotation/XMLSchema:appinfo");
				local enums = gaxb_xpath(v.xml, "./XMLSchema:restriction/XMLSchema:enumeration");

				if(appinfo ~= nil) then
					appinfo = appinfo[1].content;
				end

				if(appinfo == "ENUM" or appinfo == "NAMED_ENUM") then
					for k,v in pairs(enums) do
						gaxb_print("\t\tcase "..v.attributes.value.." = \""..v.attributes.value.."\"\n")
					end
				end
		--		if(appinfo == "ENUM_MASK") then
		--			local i = 1
		--			gaxb_print("\tpublic enum\n{\n")
		--			for k,v in pairs(enums) do
		--				gaxb_print("\t\t"..v.attributes.value.." = "..i..",\n")
		--				i = i * 2;
		--			end
		--			gaxb_print("\t};\n")
		--		end

				gaxb_print("\t}\n\n");
			end
		end
	end
%>}

@objc(<%= FULL_NAME_CAMEL %>GaxbFactory) public class <%= FULL_NAME_CAMEL %>GaxbFactory : GaxbFactory {
	public override func classWithName(name : String) -> GaxbElement? {
		switch name {<%
for k,v in pairs(schema.elements) do
	-- if not in the schema namespace, skip
	if (schema.namespace == v.namespace) then
		v.name = cleanedName(v.name);%>
		case "<%= v.name %>":
			return <%= v.name %>()<%
	end
end %>
		default:
			return nil
		}
	}
}
