<%
CAP_NAME = capitalizedString(this.namespace);
%>//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

extension <%= CAP_NAME %> {

  public class func processExpressions(_ string: String) -> String {
    return string
  }

}
