#!/bin/bash

# PlanetPlayground.playground/Pages/Styles.xcplaygroundpage
# PlanetPlayground.playground/Pages/Styles.xcplaygroundpage/Contents.swift
# PlanetPlayground.playground/Pages/Styles.xcplaygroundpage/Resources
# PlanetPlayground.playground/Pages/Styles.xcplaygroundpage/Resources/logo.png
# PlanetPlayground.playground/Pages/Styles.xcplaygroundpage/Resources/styles.xml
# PlanetPlayground.playground/Pages/Styles.xcplaygroundpage/timeline.xctimeline
# PlanetPlayground.playground/Resources
# PlanetPlayground.playground/Resources/logo.png
# PlanetPlayground.playground/Resources/styles.xml
# PlanetPlayground.playground/Sources
# PlanetPlayground.playground/Sources/PlaygroundSetup.swift
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Manifest.plist
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages/Page1.playgroundpage
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages/Page1.playgroundpage/Contents.swift
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages/Page1.playgroundpage/Manifest.plist
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages/Page1.playgroundpage/Resources
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages/Page1.playgroundpage/Resources/logo.png
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages/Page1.playgroundpage/Resources/styles.xml
# PlanetSwift.playgroundbook//Contents/Chapters/Chapter1.playgroundchapter/Pages/Page2.playgroundpage

# set -x

BOOK=PlanetSwift2.playgroundbook
SOURCES=${BOOK}/Contents/Sources
PAGES=${BOOK}/Contents/Chapters/Chapter1.playgroundchapter/Pages

mkdir -p ${SOURCES}/GaxbTypes
mkdir -p ${SOURCES}/Views
mkdir -p ${SOURCES}/Generated
mkdir -p ${BOOK}/Contents/Chapters/Chapter1.playgroundchapter/Pages
mkdir -p ${BOOK}/Contents/Resources

cp PlanetPlayground.playground/Sources/*.swift ${SOURCES}
cp ../Generated/*.swift ${SOURCES}/Generated
cp ../PlanetSwift/*.swift ${SOURCES}
cp ../PlanetSwift/GaxbTypes/*.swift ${SOURCES}/GaxbTypes
cp ../PlanetSwift/Views/*.swift ${SOURCES}/Views
cp ../AEXML/*.swift ${SOURCES}
cp PlanetPlayground.playground/Resources/* ${BOOK}/Contents/Resources


cat > ${BOOK}/Contents/Manifest.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Version</key>
    <string>1.0</string>
    <key>ContentVersion</key>
    <string>1.0</string>
    <key>Name</key>
    <string>Starter</string>
    <key>ContentIdentifier</key>
    <string>com.example.apple-samplecode.Starter</string>
    <key>DeploymentTarget</key>
    <string>ios10.0</string>
    <key>Chapters</key>
    <array>
        <string>Chapter1.playgroundchapter</string>
    </array>
</dict>
</plist>
EOF

CHAPTER_MANIFEST=${BOOK}/Contents/Chapters/Chapter1.playgroundchapter/Manifest.plist

cat > ${CHAPTER_MANIFEST} << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Version</key>
    <string>1.0</string>
    <key>Name</key>
    <string>Introduction</string>
    <key>Pages</key>
    <array>
EOF

for page in PlanetPlayground.playground/Pages/* 
do
  name=`echo $page | cut -d\/ -f 3 | cut -d\. -f1`
  echo $page
  echo "        <string>${name}.playgroundpage</string>" >> ${CHAPTER_MANIFEST}
  mkdir -p ${PAGES}/${name}.playgroundpage/Resources
  cp ${page}/Resources/* ${PAGES}/${name}.playgroundpage/Resources
  cat ${page}/Contents.swift | grep -v "import PlanetSwift" > ${PAGES}/${name}.playgroundpage/Contents.swift

  cat > ${PAGES}/${name}.playgroundpage/Manifest.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Version</key>
    <string>1.0</string>
    <key>Name</key>
    <string>${name}</string>
    <key>LiveViewMode</key>
    <string>VisibleByDefault</string>
</dict>
</plist>
EOF

done

cat >> ${CHAPTER_MANIFEST} << EOF
    </array>
</dict>
</plist>
EOF

